[package]
name = "composite_type"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
# name = "tuple"
# path = "src/tuple.rs"
# name = "struct"
# path = "src/struct.rs"
# name = "enum"
# path = "src/enum.rs" 
name = "array"
path = "src/array.rs" 
